from models.nba_games import (
    NBAGameSummary,
    TeamImpactStats,
    TeamAnalytics,
    QuarterScore
)

# -------------------------
# Game 1: Warriors Clutch Comeback Win
# -------------------------

warriors_clutch_comeback = NBAGameSummary(
    home_team="Warriors",
    away_team="Lakers",
    home_team_score=118,
    away_team_score=115,
    total_score=233,
    clutch_game=True,
    comeback_game=True,
    post_season=True,
    post_season_impact = False,

    home_impact=TeamImpactStats(
        top_points=38,
        top_rebounds=9,
        top_assists=7,
        top_steals=3,
        top_blocks=2,
        top_scorer="Stephen Curry",
        top_rebounder="Draymond Green",
        top_assister="Draymond Green",
        top_stealer="Gary Payton II",
        top_blocker="Kevon Looney",
        impact_points=12.5,
        impact_points_player="Stephen Curry",
        impact_rebounds=6.1,
        impact_rebounds_player="Draymond Green",
        impact_assists=8.3,
        impact_assists_player="Draymond Green",
    ),

    away_impact=TeamImpactStats(
        top_points=34,
        top_rebounds=11,
        top_assists=8,
        top_steals=2,
        top_blocks=1,
        top_scorer="LeBron James",
        top_rebounder="Anthony Davis",
        top_assister="LeBron James",
        top_stealer="Austin Reaves",
        top_blocker="Anthony Davis",
        impact_points=9.2,
        impact_points_player="LeBron James",
        impact_rebounds=7.4,
        impact_rebounds_player="Anthony Davis",
        impact_assists=6.9,
        impact_assists_player="LeBron James",
    ),

    home_analytics=TeamAnalytics(
        q1=QuarterScore(cumulative_score=22, points_scored=22),
        q2=QuarterScore(cumulative_score=46, points_scored=24),
        q3=QuarterScore(cumulative_score=77, points_scored=31),
        q4=QuarterScore(cumulative_score=118, points_scored=41),
        fg_percent=0.49,
        fga=89,
        fgm=44,
        three_p_percent=0.41,
        three_pa=39,
        three_pm=16,
        turnover=13,
        most_efficient_fg=0.62,
        most_efficient_fga=21,
        most_efficient_fgm=13,
        most_efficient_fg_player="Stephen Curry",
        most_efficient_3p=0.55,
        most_efficient_3pa=11,
        most_efficient_3pm=6,
        most_efficient_3p_player="Stephen Curry",
        least_efficient_fg=0.29,
        least_efficient_fga=14,
        least_efficient_fgm=4,
        least_efficient_fg_player="Andrew Wiggins",
        least_efficient_3p=0.20,
        least_efficient_3pa=5,
        least_efficient_3pm=1,
        least_efficient_3p_player="Andrew Wiggins",
        least_efficient_points=4.1,
        least_efficient_points_player="Andrew Wiggins",
    ),

    away_analytics=TeamAnalytics(
        q1=QuarterScore(cumulative_score=32, points_scored=32),
        q2=QuarterScore(cumulative_score=62, points_scored=30),
        q3=QuarterScore(cumulative_score=90, points_scored=28),
        q4=QuarterScore(cumulative_score=115, points_scored=25),
        fg_percent=0.47,
        fga=92,
        fgm=43,
        three_p_percent=0.35,
        three_pa=37,
        three_pm=13,
        turnover=15,
        most_efficient_fg=0.58,
        most_efficient_fga=19,
        most_efficient_fgm=11,
        most_efficient_fg_player="LeBron James",
        most_efficient_3p=0.42,
        most_efficient_3pa=7,
        most_efficient_3pm=3,
        most_efficient_3p_player="D'Angelo Russell",
        least_efficient_fg=0.31,
        least_efficient_fga=13,
        least_efficient_fgm=4,
        least_efficient_fg_player="Rui Hachimura",
        least_efficient_3p=0.18,
        least_efficient_3pa=6,
        least_efficient_3pm=1,
        least_efficient_3p_player="Rui Hachimura",
        least_efficient_points=3.8,
        least_efficient_points_player="Rui Hachimura",
    ),
)

# -------------------------
# Game 2: Pistons Blowout Loss (Unimportant)
# -------------------------

pistons_blowout_loss = NBAGameSummary(
    home_team="Bucks",
    away_team="Pistons",
    home_team_score=128,
    away_team_score=96,
    total_score=224,
    clutch_game=False,
    comeback_game=False,
    post_season=False,
    post_season_impact = True,

    home_impact=TeamImpactStats(
        top_points=41,
        top_rebounds=13,
        top_assists=9,
        top_steals=3,
        top_blocks=2,
        top_scorer="Giannis Antetokounmpo",
        top_rebounder="Giannis Antetokounmpo",
        top_assister="Damian Lillard",
        top_stealer="Jrue Holiday",
        top_blocker="Brook Lopez",
        impact_points=15.4,
        impact_points_player="Giannis Antetokounmpo",
        impact_rebounds=9.7,
        impact_rebounds_player="Giannis Antetokounmpo",
        impact_assists=7.8,
        impact_assists_player="Damian Lillard",
    ),

    away_impact=TeamImpactStats(
        top_points=19,
        top_rebounds=8,
        top_assists=6,
        top_steals=1,
        top_blocks=1,
        top_scorer="Cade Cunningham",
        top_rebounder="Jalen Duren",
        top_assister="Cade Cunningham",
        top_stealer="Killian Hayes",
        top_blocker="Jalen Duren",
        impact_points=4.2,
        impact_points_player="Cade Cunningham",
        impact_rebounds=5.1,
        impact_rebounds_player="Jalen Duren",
        impact_assists=4.6,
        impact_assists_player="Cade Cunningham",
    ),

    home_analytics=TeamAnalytics(
        q1=QuarterScore(34, 34),
        q2=QuarterScore(66, 32),
        q3=QuarterScore(97, 31),
        q4=QuarterScore(128, 31),
        fg_percent=0.54,
        fga=94,
        fgm=51,
        three_p_percent=0.39,
        three_pa=38,
        three_pm=15,
        turnover=11,
        most_efficient_fg=0.67,
        most_efficient_fga=24,
        most_efficient_fgm=16,
        most_efficient_fg_player="Giannis Antetokounmpo",
        most_efficient_3p=0.44,
        most_efficient_3pa=9,
        most_efficient_3pm=4,
        most_efficient_3p_player="Damian Lillard",
        least_efficient_fg=0.31,
        least_efficient_fga=13,
        least_efficient_fgm=4,
        least_efficient_fg_player="Pat Connaughton",
        least_efficient_3p=0.25,
        least_efficient_3pa=4,
        least_efficient_3pm=1,
        least_efficient_3p_player="Pat Connaughton",
        least_efficient_points=3.1,
        least_efficient_points_player="Pat Connaughton",
    ),

    away_analytics=TeamAnalytics(
        q1=QuarterScore(20, 20),
        q2=QuarterScore(42, 22),
        q3=QuarterScore(68, 26),
        q4=QuarterScore(96, 28),
        fg_percent=0.41,
        fga=86,
        fgm=35,
        three_p_percent=0.30,
        three_pa=33,
        three_pm=10,
        turnover=18,
        most_efficient_fg=0.46,
        most_efficient_fga=17,
        most_efficient_fgm=8,
        most_efficient_fg_player="Cade Cunningham",
        most_efficient_3p=0.33,
        most_efficient_3pa=6,
        most_efficient_3pm=2,
        most_efficient_3p_player="Bojan Bogdanovic",
        least_efficient_fg=0.28,
        least_efficient_fga=12,
        least_efficient_fgm=3,
        least_efficient_fg_player="Killian Hayes",
        least_efficient_3p=0.17,
        least_efficient_3pa=6,
        least_efficient_3pm=1,
        least_efficient_3p_player="Killian Hayes",
        least_efficient_points=2.9,
        least_efficient_points_player="Killian Hayes",
    ),
)

# -------------------------
# Game 3: Neutral High-Scoring Thriller
# -------------------------

nets_hawks_shootout = NBAGameSummary(
    home_team="Nets",
    away_team="Hawks",
    home_team_score=134,
    away_team_score=131,
    total_score=265,
    clutch_game=True,
    comeback_game=False,
    post_season=True,
    post_season_impact = False,

    home_impact=TeamImpactStats(
        top_points=39,
        top_rebounds=10,
        top_assists=9,
        top_steals=2,
        top_blocks=1,
        top_scorer="Mikal Bridges",
        top_rebounder="Nic Claxton",
        top_assister="Ben Simmons",
        top_stealer="Mikal Bridges",
        top_blocker="Nic Claxton",
        impact_points=11.6,
        impact_points_player="Mikal Bridges",
        impact_rebounds=6.8,
        impact_rebounds_player="Nic Claxton",
        impact_assists=7.5,
        impact_assists_player="Ben Simmons",
    ),

    away_impact=TeamImpactStats(
        top_points=44,
        top_rebounds=7,
        top_assists=12,
        top_steals=2,
        top_blocks=0,
        top_scorer="Trae Young",
        top_rebounder="Clint Capela",
        top_assister="Trae Young",
        top_stealer="Dejounte Murray",
        top_blocker="Clint Capela",
        impact_points=14.9,
        impact_points_player="Trae Young",
        impact_rebounds=8.2,
        impact_rebounds_player="Clint Capela",
        impact_assists=10.3,
        impact_assists_player="Trae Young",
    ),

    home_analytics=TeamAnalytics(
        q1=QuarterScore(33, 33),
        q2=QuarterScore(68, 35),
        q3=QuarterScore(100, 32),
        q4=QuarterScore(134, 34),
        fg_percent=0.52,
        fga=96,
        fgm=50,
        three_p_percent=0.43,
        three_pa=42,
        three_pm=18,
        turnover=12,
        most_efficient_fg=0.61,
        most_efficient_fga=22,
        most_efficient_fgm=14,
        most_efficient_fg_player="Mikal Bridges",
        most_efficient_3p=0.48,
        most_efficient_3pa=10,
        most_efficient_3pm=5,
        most_efficient_3p_player="Cam Johnson",
        least_efficient_fg=0.33,
        least_efficient_fga=12,
        least_efficient_fgm=4,
        least_efficient_fg_player="Dorian Finney-Smith",
        least_efficient_3p=0.27,
        least_efficient_3pa=7,
        least_efficient_3pm=2,
        least_efficient_3p_player="Dorian Finney-Smith",
        least_efficient_points=3.7,
        least_efficient_points_player="Dorian Finney-Smith",
    ),

    away_analytics=TeamAnalytics(
        q1=QuarterScore(36, 36),
        q2=QuarterScore(70, 34),
        q3=QuarterScore(100, 30),
        q4=QuarterScore(131, 31),
        fg_percent=0.51,
        fga=98,
        fgm=50,
        three_p_percent=0.41,
        three_pa=39,
        three_pm=16,
        turnover=14,
        most_efficient_fg=0.57,
        most_efficient_fga=26,
        most_efficient_fgm=15,
        most_efficient_fg_player="Trae Young",
        most_efficient_3p=0.46,
        most_efficient_3pa=11,
        most_efficient_3pm=5,
        most_efficient_3p_player="Bogdan Bogdanovic",
        least_efficient_fg=0.35,
        least_efficient_fga=14,
        least_efficient_fgm=5,
        least_efficient_fg_player="De'Andre Hunter",
        least_efficient_3p=0.29,
        least_efficient_3pa=7,
        least_efficient_3pm=2,
        least_efficient_3p_player="De'Andre Hunter",
        least_efficient_points=4.0,
        least_efficient_points_player="De'Andre Hunter",
    ),
)

# -------------------------
# Game 4: Real data from ESPN API (fetchers/nba_data.py)
# Oklahoma City Thunder vs San Antonio Spurs — playoff game
# -------------------------

espn_extracted_game = NBAGameSummary(
    home_team="Oklahoma City Thunder",
    away_team="San Antonio Spurs",
    home_team_score=122,
    away_team_score=113,
    total_score=235,
    clutch_game=True,
    comeback_game=False,
    post_season=True,
    post_season_impact=True,

    home_impact=TeamImpactStats(
        top_points=30,
        top_rebounds=13,
        top_assists=9,
        top_steals=4,
        top_blocks=2,
        top_scorer="Shai Gilgeous-Alexander",
        top_rebounder="Isaiah Hartenstein",
        top_assister="Shai Gilgeous-Alexander",
        top_stealer="Cason Wallace",
        top_blocker="Shai Gilgeous-Alexander",
        impact_points=0.79,
        impact_points_player="Shai Gilgeous-Alexander",
        impact_rebounds=0.48,
        impact_rebounds_player="Isaiah Hartenstein",
        impact_assists=0.24,
        impact_assists_player="Shai Gilgeous-Alexander",
    ),

    away_impact=TeamImpactStats(
        top_points=25,
        top_rebounds=17,
        top_assists=8,
        top_steals=1,
        top_blocks=4,
        top_scorer="Stephon Castle",
        top_rebounder="Victor Wembanyama",
        top_assister="Stephon Castle",
        top_stealer="Julian Champagnie",
        top_blocker="Victor Wembanyama",
        impact_points=0.86,
        impact_points_player="Jordan McLaughlin",
        impact_rebounds=0.46,
        impact_rebounds_player="Victor Wembanyama",
        impact_assists=0.21,
        impact_assists_player="Stephon Castle",
    ),

    home_analytics=TeamAnalytics(
        q1=QuarterScore(cumulative_score=31, points_scored=31),
        q2=QuarterScore(cumulative_score=62, points_scored=31),
        q3=QuarterScore(cumulative_score=96, points_scored=34),
        q4=QuarterScore(cumulative_score=122, points_scored=26),
        fg_percent=47.87,
        fga=94,
        fgm=45,
        three_p_percent=36.11,
        three_pa=36,
        three_pm=13,
        turnover=9,
        most_efficient_fg=71.43,
        most_efficient_fga=7,
        most_efficient_fgm=5,
        most_efficient_fg_player="Alex Caruso",
        most_efficient_3p=75.0,
        most_efficient_3pa=4,
        most_efficient_3pm=3,
        most_efficient_3p_player="Alex Caruso",
        least_efficient_fg=28.57,
        least_efficient_fga=14,
        least_efficient_fgm=4,
        least_efficient_fg_player="Jared McCain",
        least_efficient_3p=0.0,
        least_efficient_3pa=3,
        least_efficient_3pm=0,
        least_efficient_3p_player="Shai Gilgeous-Alexander",
        least_efficient_points=0.0,
        least_efficient_points_player="Isaiah Joe",
    ),

    away_analytics=TeamAnalytics(
        q1=QuarterScore(cumulative_score=31, points_scored=31),
        q2=QuarterScore(cumulative_score=51, points_scored=20),
        q3=QuarterScore(cumulative_score=88, points_scored=37),
        q4=QuarterScore(cumulative_score=113, points_scored=25),
        fg_percent=48.81,
        fga=84,
        fgm=41,
        three_p_percent=40.0,
        three_pa=40,
        three_pm=16,
        turnover=21,
        most_efficient_fg=58.82,
        most_efficient_fga=17,
        most_efficient_fgm=10,
        most_efficient_fg_player="Stephon Castle",
        most_efficient_3p=50.0,
        most_efficient_3pa=12,
        most_efficient_3pm=6,
        most_efficient_3p_player="Devin Vassell",
        least_efficient_fg=25.0,
        least_efficient_fga=8,
        least_efficient_fgm=2,
        least_efficient_fg_player="Julian Champagnie",
        least_efficient_3p=14.29,
        least_efficient_3pa=7,
        least_efficient_3pm=1,
        least_efficient_3p_player="Julian Champagnie",
        least_efficient_points=0.0,
        least_efficient_points_player="Carter Bryant",
    ),
)

# -------------------------
# Collection for easy iteration
# -------------------------

FAKE_NBA_GAMES = [
    warriors_clutch_comeback,
    pistons_blowout_loss,
    nets_hawks_shootout,
    espn_extracted_game,
]